name: Build LaTeX document
on:
  push:
    branches:
      - main  # Adjust if needed
    paths-ignore:
      - '**.pdf'
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: proposal.tex
      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ env.timestamp }}
          name: Release ${{ env.timestamp }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      
      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v2
        with:
          files: proposal.pdf
          tag_name: release-${{ env.timestamp }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
